apiVersion: v1
kind: Service
metadata:
  name: springboot-service
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80         # Port externe accessible via le LoadBalancer
      targetPort: 8089 # Port exposé par l'application dans le conteneur
  type: LoadBalancer